- name: Run tests with coverage
  run: |
    pip install coveralls
    coverage run -m pytest tests.py --cov=infsumpy
    coverage xml

- name: Upload coverage to Coveralls
  uses: coverallsapp/github-action@v2
  with:
    format: cobertura
    file: coverage.xml